name: Go

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Fetch dependencies
      run: go get -d
    - name: Build
      run: go build
    
  run:
    runs-on: self-hosted
    steps: 
    - name: Run
      run: ./binalysis &